ALTER TABLE IF EXISTS  notes
  DROP COLUMN folder;

DROP TABLE IF EXISTS folders;
DROP TABLE IF EXISTS notes;

CREATE TABLE folders (
  id  INTEGER  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_name TEXT NOT NULL
);

CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  modified_date DATE DEFAULT now(),
  content TEXT
);

--psql -U dunder_mifflin - d noteful -f "C:\Users\Nick\Desktop\nodeProjects\noteful-api\sql-scripts \create_noteful_db.sql"
